# Generated by Django 5.2.1 on 2025-10-13 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0003_alter_utilisateur_doit_changer_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalutilisateur',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
