# Generated by Django 4.2.12 on 2025-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0001_initial'),
        ('Utilisateur', '0004_alter_historicalutilisateur_id_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ['utilisateur__last_name'], 'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.AlterModelOptions(
            name='historicalenseignant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Enseignant', 'verbose_name_plural': 'historical Enseignants'},
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='autres_specialites',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='specialites',
        ),
        migrations.RemoveField(
            model_name='historicalenseignant',
            name='autres_specialites',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='autres_matieres',
            field=models.CharField(blank=True, help_text='Autres matières enseignées', max_length=255),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='bureau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(blank=True, help_text='Ex: Professeur, Assistant', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='Cours.matiere'),
        ),
        migrations.AddField(
            model_name='historicalenseignant',
            name='autres_matieres',
            field=models.CharField(blank=True, help_text='Autres matières enseignées', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalenseignant',
            name='bureau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalenseignant',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalenseignant',
            name='grade',
            field=models.CharField(blank=True, help_text='Ex: Professeur, Assistant', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Specialite',
        ),
    ]
