# Generated by Django 4.2.12 on 2025-11-12 19:22

from django.db import migrations, models
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('objectifs', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_cours', models.CharField(choices=[('COURS', 'Cours'), ('TP', 'Travaux Pratiques'), ('TD', 'Travaux Dirigés'), ('EXAMEN', 'Examen'), ('COMPO', 'Composition'), ('PROJET', 'Projet'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DEVOIR', 'Devoir'), ('DS', 'Devoir Surveillé'), ('COMPO', 'Composition'), ('EXAMEN', 'Examen'), ('ORAL', 'Oral'), ('TP', 'Travaux Pratiques')], default='DEVOIR', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('coefficient', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalChapitre',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical chapitre',
                'verbose_name_plural': 'historical chapitres',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCours',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_cours', models.CharField(choices=[('COURS', 'Cours'), ('TP', 'Travaux Pratiques'), ('TD', 'Travaux Dirigés'), ('EXAMEN', 'Examen'), ('COMPO', 'Composition'), ('PROJET', 'Projet'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cours',
                'verbose_name_plural': 'historical courss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEvaluation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DEVOIR', 'Devoir'), ('DS', 'Devoir Surveillé'), ('COMPO', 'Composition'), ('EXAMEN', 'Examen'), ('ORAL', 'Oral'), ('TP', 'Travaux Pratiques')], default='DEVOIR', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical evaluation',
                'verbose_name_plural': 'historical evaluations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical note',
                'verbose_name_plural': 'historical notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(choices=[('COURS', 'Salle de cours'), ('INFO', 'Salle informatique'), ('LABO', 'Laboratoire'), ('AMPHI', 'Amphithéâtre'), ('REUNION', 'Salle de réunion'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=20)),
                ('batiment', models.CharField(blank=True, max_length=100, null=True)),
                ('etage', models.PositiveIntegerField(blank=True, null=True)),
                ('projecteur', models.BooleanField(default=False)),
                ('climatisation', models.BooleanField(default=False)),
                ('ordinateurs', models.BooleanField(default=False)),
                ('tableau_blanc', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical salle',
                'verbose_name_plural': 'historical salles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Ex: MAT101', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatiereClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('volume_horaire', models.PositiveIntegerField(default=0, help_text='Heures par semaine')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('COURS', 'Salle de cours'), ('INFO', 'Salle informatique'), ('LABO', 'Laboratoire'), ('AMPHI', 'Amphithéâtre'), ('REUNION', 'Salle de réunion'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=20)),
                ('batiment', models.CharField(blank=True, max_length=100, null=True)),
                ('etage', models.PositiveIntegerField(blank=True, null=True)),
                ('projecteur', models.BooleanField(default=False)),
                ('climatisation', models.BooleanField(default=False)),
                ('ordinateurs', models.BooleanField(default=False)),
                ('tableau_blanc', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
