# Generated by Django 4.2.12 on 2025-11-11 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Utilisateur', '0004_alter_historicalutilisateur_id_alter_utilisateur_id'),
        ('Formation', '0003_historicalanneeacademique_historicalclasse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DEVOIR', 'Devoir'), ('DS', 'Devoir Surveillé'), ('COMPO', 'Composition'), ('EXAMEN', 'Examen'), ('ORAL', 'Oral'), ('TP', 'Travaux Pratiques')], default='DEVOIR', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Formation.classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('COURS', 'Salle de cours'), ('INFO', 'Salle informatique'), ('LABO', 'Laboratoire'), ('AMPHI', 'Amphithéâtre'), ('REUNION', 'Salle de réunion'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=20)),
                ('batiment', models.CharField(blank=True, max_length=100, null=True)),
                ('etage', models.PositiveIntegerField(blank=True, null=True)),
                ('projecteur', models.BooleanField(default=False)),
                ('climatisation', models.BooleanField(default=False)),
                ('ordinateurs', models.BooleanField(default=False)),
                ('tableau_blanc', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Ex: MAT101', max_length=20, unique=True)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('volume_horaire', models.PositiveIntegerField(default=0, help_text='Heures par semaine')),
                ('description', models.TextField(blank=True, null=True)),
                ('classes', models.ManyToManyField(related_name='matieres', to='Formation.classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(choices=[('COURS', 'Salle de cours'), ('INFO', 'Salle informatique'), ('LABO', 'Laboratoire'), ('AMPHI', 'Amphithéâtre'), ('REUNION', 'Salle de réunion'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=20)),
                ('batiment', models.CharField(blank=True, max_length=100, null=True)),
                ('etage', models.PositiveIntegerField(blank=True, null=True)),
                ('projecteur', models.BooleanField(default=False)),
                ('climatisation', models.BooleanField(default=False)),
                ('ordinateurs', models.BooleanField(default=False)),
                ('tableau_blanc', models.BooleanField(default=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical salle',
                'verbose_name_plural': 'historical salles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('etudiant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Utilisateur.etudiant')),
                ('evaluation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.evaluation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical note',
                'verbose_name_plural': 'historical notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMatiere',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Ex: MAT101', max_length=20)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('volume_horaire', models.PositiveIntegerField(default=0, help_text='Heures par semaine')),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical matiere',
                'verbose_name_plural': 'historical matieres',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEvaluation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DEVOIR', 'Devoir'), ('DS', 'Devoir Surveillé'), ('COMPO', 'Composition'), ('EXAMEN', 'Examen'), ('ORAL', 'Oral'), ('TP', 'Travaux Pratiques')], default='DEVOIR', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.classe')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.matiere')),
            ],
            options={
                'verbose_name': 'historical evaluation',
                'verbose_name_plural': 'historical evaluations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCours',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_cours', models.CharField(choices=[('COURS', 'Cours'), ('TP', 'Travaux Pratiques'), ('TD', 'Travaux Dirigés'), ('EXAMEN', 'Examen'), ('COMPO', 'Composition'), ('PROJET', 'Projet'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.classe')),
                ('enseignant', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Utilisateur.enseignant')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.matiere')),
                ('salle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.salle')),
            ],
            options={
                'verbose_name': 'historical cours',
                'verbose_name_plural': 'historical courss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalChapitre',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.matiere')),
            ],
            options={
                'verbose_name': 'historical chapitre',
                'verbose_name_plural': 'historical chapitres',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Cours.matiere'),
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_cours', models.CharField(choices=[('COURS', 'Cours'), ('TP', 'Travaux Pratiques'), ('TD', 'Travaux Dirigés'), ('EXAMEN', 'Examen'), ('COMPO', 'Composition'), ('PROJET', 'Projet'), ('AUTRE', 'Autre')], default='COURS', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Formation.classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='Utilisateur.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Cours.matiere')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='Cours.salle')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='Cours.matiere')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Utilisateur.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Cours.evaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'etudiant')},
            },
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('salle', 'date', 'heure_debut', 'heure_fin'), name='unique_salle_usage'),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('classe', 'date', 'heure_debut', 'heure_fin'), name='unique_classe_usage'),
        ),
    ]
