# Generated by Django 4.2.12 on 2025-11-12 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Formation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cours', '0001_initial'),
        ('Utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Utilisateur.etudiant'),
        ),
        migrations.AddField(
            model_name='note',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Cours.evaluation'),
        ),
        migrations.AddField(
            model_name='matiereclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_classes', to='Formation.classe'),
        ),
        migrations.AddField(
            model_name='matiereclasse',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_classes', to='Cours.matiere'),
        ),
        migrations.AddField(
            model_name='historicalsalle',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='etudiant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Utilisateur.etudiant'),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='evaluation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.evaluation'),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalevaluation',
            name='classe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.classe'),
        ),
        migrations.AddField(
            model_name='historicalevaluation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalevaluation',
            name='matiere',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.matiere'),
        ),
        migrations.AddField(
            model_name='historicalcours',
            name='enseignement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.enseignement'),
        ),
        migrations.AddField(
            model_name='historicalcours',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcours',
            name='salle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.salle'),
        ),
        migrations.AddField(
            model_name='historicalchapitre',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalchapitre',
            name='matiere',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.matiere'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Formation.classe'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Cours.matiere'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='Utilisateur.enseignant'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='matiere_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='Cours.matiereclasse'),
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='Cours.enseignement'),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='Cours.salle'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='Cours.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('evaluation', 'etudiant')},
        ),
        migrations.AlterUniqueTogether(
            name='matiereclasse',
            unique_together={('matiere', 'classe')},
        ),
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('enseignant', 'matiere_classe', 'annee_academique')},
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('salle', 'date', 'heure_debut', 'heure_fin'), name='unique_salle_usage'),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('enseignement', 'date', 'heure_debut', 'heure_fin'), name='unique_classe_usage'),
        ),
    ]
