# Generated by Django 4.2.12 on 2025-11-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalchapitre',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchapitre',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='historicalevaluation',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='historicalevaluation',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='historicalevaluation',
            name='matiere',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='matiereclasse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='Cours.matiereclasse'),
        ),
        migrations.AddField(
            model_name='historicalevaluation',
            name='matiereclasse',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Cours.matiereclasse'),
        ),
        migrations.DeleteModel(
            name='Chapitre',
        ),
        migrations.DeleteModel(
            name='HistoricalChapitre',
        ),
    ]
