# Generated by Django 4.2.12 on 2025-11-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0002_initial'),
        ('Cours', '0006_alter_enseignement_annee_academique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignement',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.anneeacademique'),
        ),
    ]
