# Generated by Django 5.2.1 on 2025-06-19 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type', models.CharField(choices=[('CO', 'Support de cours'), ('DE', 'Devoir'), ('AN', 'Annonce')], max_length=2)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('LABO', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('ASSURANCE', 'Assurance'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA (utiliser un point comme séparateur décimal)', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('recurrent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('abandon', 'Abandon'), ('suspendu', 'Suspendu')], default='inscrit', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('type', models.CharField(choices=[('EM', 'Email'), ('SM', 'SMS'), ('PU', 'Notification push')], max_length=2)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('CB', 'Carte Bancaire'), ('VI', 'Virement'), ('ES', 'Espèces')], max_length=2)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Finance.document')),
                ('date_rendu', models.DateTimeField()),
                ('est_rendu', models.BooleanField(default=False)),
            ],
            bases=('Finance.document',),
        ),
    ]
