# Generated by Django 4.2.12 on 2025-11-12 19:22

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('type', models.CharField(choices=[('CO', 'Support de cours'), ('DE', 'Devoir'), ('AN', 'Annonce'), ('IN', 'Inscription')], max_length=2)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('formulaire', "Formulaire d'inscription"), ('naissance', 'Acte de naissance'), ('cni', "Carte nationale d'identité / Certificat d'identification"), ('parent_identite', 'Identité des parents ou tuteurs'), ('bulletin', 'Dernier bulletin de notes / Relevé'), ('diplome', 'Diplôme ou attestation du niveau'), ('certificat_scolarite', 'Certificat de scolarité'), ('motivation_cv', 'Lettre de motivation ou CV'), ('frais', 'Quittance de paiement / reçu')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents_inscription/')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('LABO', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('ASSURANCE', 'Assurance'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA (utiliser un point comme séparateur décimal)', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('recurrent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFrais',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('LABO', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('ASSURANCE', 'Assurance'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA (utiliser un point comme séparateur décimal)', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('recurrent', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical frais',
                'verbose_name_plural': 'historical fraiss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInscription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('motif', models.TextField(blank=True, null=True)),
                ('Etablissement_accuiel', models.CharField(blank=True, max_length=100, null=True)),
                ('date_inscription', models.DateField(blank=True, editable=False)),
                ('date_evenement', models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de l'événement")),
                ('duree', models.PositiveIntegerField(blank=True, help_text='Durée en jours (ex: suspension)', null=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('abandon', 'Abandon'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('en_attente', 'En attente de validation'), ('transfert', 'Transféré'), ('diplome', 'Diplômé'), ('redoublant', 'Redoublant'), ('reserviste', 'Réserviste')], default='inscrit', help_text="Sélectionnez le statut de l'étudiant", max_length=20)),
                ('resultat_annee_precedente', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical inscription',
                'verbose_name_plural': 'historical inscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaiement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('CB', 'Carte Bancaire'), ('ES', 'Espèces'), ('MM', 'Mobile Money (Orange Money, Moov Money , Telecel Money)'), ('CH', 'Chèque'), ('PP', 'PayPal')], max_length=2)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('date_paiement', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical paiement',
                'verbose_name_plural': 'historical paiements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, null=True)),
                ('Etablissement_accuiel', models.CharField(blank=True, max_length=100, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('date_evenement', models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de l'événement")),
                ('duree', models.PositiveIntegerField(blank=True, help_text='Durée en jours (ex: suspension)', null=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('abandon', 'Abandon'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('en_attente', 'En attente de validation'), ('transfert', 'Transféré'), ('diplome', 'Diplômé'), ('redoublant', 'Redoublant'), ('reserviste', 'Réserviste')], default='inscrit', help_text="Sélectionnez le statut de l'étudiant", max_length=20)),
                ('resultat_annee_precedente', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('type', models.CharField(choices=[('EM', 'Email'), ('SM', 'SMS'), ('PU', 'Notification push')], max_length=2)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('CB', 'Carte Bancaire'), ('ES', 'Espèces'), ('MM', 'Mobile Money (Orange Money, Moov Money , Telecel Money)'), ('CH', 'Chèque'), ('PP', 'PayPal')], max_length=2)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Finance.document')),
                ('date_rendu', models.DateTimeField()),
                ('est_rendu', models.BooleanField(default=False)),
            ],
            bases=('Finance.document',),
        ),
    ]
