# Generated by Django 5.2.1 on 2025-07-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('CB', 'Carte Bancaire'), ('ES', 'Espèces'), ('MM', 'Mobile Money (Orange Money, Moov Money , Telecel Monet)'), ('CH', 'Chèque'), ('PP', 'PayPal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
