# Generated by Django 5.2.1 on 2025-07-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_alter_paiement_methode_alter_paiement_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_evenement',
            field=models.DateField(blank=True, help_text="Date liée à l'événement (ex: exclusion, suspension, abandon, etc.)", null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='doucument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='Finance.document'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='duree',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en jours (ex: suspension)', null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='resultat_annee_precedente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('CO', 'Support de cours'), ('DE', 'Devoir'), ('AN', 'Annonce'), ('IN', 'Inscription')], max_length=2),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('abandon', 'Abandon'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('demission', 'Démissionnaire'), ('en_attente', 'En attente de validation'), ('transfert', 'Transféré'), ('diplome', 'Diplômé'), ('redoublant', 'Redoublant'), ('reserviste', 'Réserviste')], default='inscrit', max_length=20),
        ),
    ]
