# Generated by Django 5.2.1 on 2025-07-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_inscription_date_evenement_inscription_doucument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='doucument',
        ),
        migrations.AddField(
            model_name='inscription',
            name='Etablissement_accuiel',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('abandon', 'Abandon'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('en_attente', 'En attente de validation'), ('transfert', 'Transféré'), ('diplome', 'Diplômé'), ('redoublant', 'Redoublant'), ('reserviste', 'Réserviste')], default='inscrit', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('formulaire', "Formulaire d'inscription"), ('naissance', 'Acte de naissance'), ('cni', "Carte nationale d'identité / Certificat d'identification"), ('parent_identite', 'Identité des parents ou tuteurs'), ('bulletin', 'Dernier bulletin de notes / Relevé'), ('diplome', 'Diplôme ou attestation du niveau'), ('certificat_scolarite', 'Certificat de scolarité'), ('motivation_cv', 'Lettre de motivation ou CV'), ('frais', 'Quittance de paiement / reçu')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents_inscription/')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_inscription', to='Finance.inscription')),
            ],
        ),
    ]
