# Generated by Django 5.2.1 on 2025-07-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_remove_inscription_doucument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='Etablissement_accuiel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
