# Generated by Django 5.2.1 on 2025-07-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0006_alter_inscription_etablissement_accuiel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscription',
            name='unique_inscription_par_annee',
        ),
    ]
