# Generated by Django 5.2.1 on 2025-07-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0007_remove_inscription_unique_inscription_par_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_evenement',
            field=models.DateTimeField(blank=True, help_text="Date liée à l'événement (ex: exclusion, suspension, abandon, etc.)", null=True),
        ),
    ]
