# Generated by Django 5.2.1 on 2025-07-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0008_alter_inscription_date_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_evenement',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de l'événement"),
        ),
    ]
