# Generated by Django 5.2.1 on 2025-10-02 17:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0011_alter_inscription_classe_alter_inscription_parcours'),
        ('Formation', '0003_historicalanneeacademique_historicalclasse_and_more'),
        ('Utilisateur', '0003_alter_utilisateur_doit_changer_mot_de_passe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='Utilisateur.etudiant'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('abandon', 'Abandon'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('en_attente', 'En attente de validation'), ('transfert', 'Transféré'), ('diplome', 'Diplômé'), ('redoublant', 'Redoublant'), ('reserviste', 'Réserviste')], default='inscrit', help_text="Sélectionnez le statut de l'étudiant", max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalFrais',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('INSCRIPTION', 'Inscription'), ('LABO', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('ASSURANCE', 'Assurance'), ('AUTRE', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA (utiliser un point comme séparateur décimal)', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('recurrent', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.classe')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical frais',
                'verbose_name_plural': 'historical fraiss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInscription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('motif', models.TextField(blank=True, null=True)),
                ('Etablissement_accuiel', models.CharField(blank=True, max_length=100, null=True)),
                ('date_inscription', models.DateField(blank=True, editable=False)),
                ('date_evenement', models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de l'événement")),
                ('duree', models.PositiveIntegerField(blank=True, help_text='Durée en jours (ex: suspension)', null=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('abandon', 'Abandon'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('en_attente', 'En attente de validation'), ('transfert', 'Transféré'), ('diplome', 'Diplômé'), ('redoublant', 'Redoublant'), ('reserviste', 'Réserviste')], default='inscrit', help_text="Sélectionnez le statut de l'étudiant", max_length=20)),
                ('resultat_annee_precedente', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('annee_academique', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.anneeacademique')),
                ('classe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.classe')),
                ('etudiant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Utilisateur.etudiant')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parcours', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.parcours')),
            ],
            options={
                'verbose_name': 'historical inscription',
                'verbose_name_plural': 'historical inscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaiement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('CB', 'Carte Bancaire'), ('ES', 'Espèces'), ('MM', 'Mobile Money (Orange Money, Moov Money , Telecel Monet)'), ('CH', 'Chèque'), ('PP', 'PayPal')], max_length=2)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('date_paiement', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('etudiant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Utilisateur.etudiant')),
                ('frais', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Finance.frais')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paiement',
                'verbose_name_plural': 'historical paiements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
