# Generated by Django 5.2.1 on 2025-10-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0012_alter_inscription_etudiant_alter_inscription_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaiement',
            name='methode',
            field=models.CharField(choices=[('CB', 'Carte Bancaire'), ('ES', 'Espèces'), ('MM', 'Mobile Money (Orange Money, Moov Money , Telecel Money)'), ('CH', 'Chèque'), ('PP', 'PayPal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('CB', 'Carte Bancaire'), ('ES', 'Espèces'), ('MM', 'Mobile Money (Orange Money, Moov Money , Telecel Money)'), ('CH', 'Chèque'), ('PP', 'PayPal')], max_length=2),
        ),
    ]
