BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Finance_devoir" ("document_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "Finance_document" ("id") DEFERRABLE INITIALLY DEFERRED, "date_rendu" datetime NOT NULL, "est_rendu" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "Finance_document" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "titre" varchar(200) NOT NULL, "fichier" varchar(100) NOT NULL, "type" varchar(2) NOT NULL, "date_upload" datetime NOT NULL, "auteur_id" bigint NOT NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Finance_documentinscription" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "type_document" varchar(50) NOT NULL, "fichier" varchar(100) NOT NULL, "date_depot" datetime NOT NULL, "inscription_id" bigint NOT NULL REFERENCES "Finance_inscription" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Finance_frais" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "libelle" varchar(20) NOT NULL, "montant" decimal NOT NULL, "description" text NULL, "recurrent" bool NOT NULL, "classe_id" bigint NOT NULL REFERENCES "Formation_classe" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Finance_historicalfrais" ("id" bigint NOT NULL, "libelle" varchar(20) NOT NULL, "montant" decimal NOT NULL, "description" text NULL, "recurrent" bool NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "classe_id" bigint NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Finance_historicalinscription" ("id" bigint NOT NULL, "motif" text NULL, "Etablissement_accuiel" varchar(100) NULL, "date_inscription" date NOT NULL, "date_evenement" datetime NULL, "duree" integer unsigned NULL CHECK ("duree" >= 0), "statut" varchar(20) NOT NULL, "resultat_annee_precedente" varchar(100) NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "annee_academique_id" bigint NULL, "classe_id" bigint NULL, "etudiant_id" bigint NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "parcours_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "Finance_historicalpaiement" ("id" bigint NOT NULL, "montant" decimal NOT NULL, "methode" varchar(2) NOT NULL, "reference" varchar(50) NOT NULL, "date_paiement" datetime NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "etudiant_id" bigint NULL, "frais_id" bigint NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Finance_inscription" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date_inscription" date NOT NULL, "statut" varchar(20) NOT NULL, "annee_academique_id" bigint NULL REFERENCES "Formation_anneeacademique" ("id") DEFERRABLE INITIALLY DEFERRED, "classe_id" bigint NULL REFERENCES "Formation_classe" ("id") DEFERRABLE INITIALLY DEFERRED, "parcours_id" bigint NULL REFERENCES "Formation_parcours" ("id") DEFERRABLE INITIALLY DEFERRED, "date_evenement" datetime NULL, "duree" integer unsigned NULL CHECK ("duree" >= 0), "motif" text NULL, "resultat_annee_precedente" varchar(100) NULL, "Etablissement_accuiel" varchar(100) NULL, "etudiant_id" bigint NULL REFERENCES "Utilisateur_etudiant" ("utilisateur_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Finance_notification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "contenu" text NOT NULL, "type" varchar(2) NOT NULL, "date_envoi" datetime NOT NULL, "est_lu" bool NOT NULL, "utilisateur_id" bigint NOT NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Finance_paiement" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "montant" decimal NOT NULL, "methode" varchar(2) NOT NULL, "reference" varchar(50) NOT NULL UNIQUE, "date_paiement" datetime NOT NULL, "etudiant_id" bigint NOT NULL REFERENCES "Utilisateur_etudiant" ("utilisateur_id") DEFERRABLE INITIALLY DEFERRED, "frais_id" bigint NOT NULL REFERENCES "Finance_frais" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Formation_anneeacademique" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nom" varchar(20) NOT NULL UNIQUE, "date_debut" date NOT NULL, "date_fin" date NOT NULL, "classes_standards_creees" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "Formation_classe" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nom" varchar(100) NOT NULL, "ordre" integer NOT NULL, "annee_academique_id" bigint NOT NULL REFERENCES "Formation_anneeacademique" ("id") DEFERRABLE INITIALLY DEFERRED, "formation_id" bigint NOT NULL REFERENCES "Formation_formation" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Formation_formation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nom" varchar(100) NOT NULL, "est_professionnelle" bool NOT NULL, "avec_classes" bool NOT NULL, "parcours_id" bigint NOT NULL REFERENCES "Formation_parcours" ("id") DEFERRABLE INITIALLY DEFERRED, "duree" integer NULL);
CREATE TABLE IF NOT EXISTS "Formation_historicalanneeacademique" ("id" bigint NOT NULL, "nom" varchar(20) NOT NULL, "date_debut" date NOT NULL, "date_fin" date NOT NULL, "classes_standards_creees" bool NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Formation_historicalclasse" ("id" bigint NOT NULL, "nom" varchar(100) NOT NULL, "ordre" integer NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "annee_academique_id" bigint NULL, "formation_id" bigint NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Formation_historicalformation" ("id" bigint NOT NULL, "nom" varchar(100) NOT NULL, "duree" integer NULL, "est_professionnelle" bool NOT NULL, "avec_classes" bool NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "parcours_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "Formation_historicalparcours" ("id" bigint NOT NULL, "nom" varchar(100) NOT NULL, "code_serie" varchar(3) NULL, "structure_classes" text NOT NULL CHECK ((JSON_VALID("structure_classes") OR "structure_classes" IS NULL)), "diplome_final" varchar(100) NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "specification_id" bigint NULL, "type_formation_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "Formation_parcours" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nom" varchar(100) NOT NULL, "code_serie" varchar(3) NULL, "structure_classes" text NOT NULL CHECK ((JSON_VALID("structure_classes") OR "structure_classes" IS NULL)), "diplome_final" varchar(100) NULL, "specification_id" bigint NULL REFERENCES "Formation_specification" ("id") DEFERRABLE INITIALLY DEFERRED, "type_formation_id" bigint NOT NULL REFERENCES "Formation_typeformation" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Formation_specification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(10) NOT NULL UNIQUE, "nom" varchar(50) NOT NULL);
CREATE TABLE IF NOT EXISTS "Formation_typeformation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(10) NOT NULL UNIQUE, "nom" varchar(100) NOT NULL, "liste_classe" text NOT NULL CHECK ((JSON_VALID("liste_classe") OR "liste_classe" IS NULL)));
CREATE TABLE IF NOT EXISTS "Permissions_Manager_metapermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "description" text NOT NULL, "roles_autorises" varchar(200) NOT NULL, "est_active" bool NOT NULL, "date_creation" datetime NOT NULL, "date_modification" datetime NOT NULL, "permission_id" integer NOT NULL UNIQUE REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_adminsysteme" ("utilisateur_id" bigint NOT NULL PRIMARY KEY REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_agentadministration" ("utilisateur_id" bigint NOT NULL PRIMARY KEY REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_agentadministration_fonctions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "agentadministration_id" bigint NOT NULL REFERENCES "Utilisateur_agentadministration" ("utilisateur_id") DEFERRABLE INITIALLY DEFERRED, "fonctionagent_id" bigint NOT NULL REFERENCES "Utilisateur_fonctionagent" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_enseignant" ("utilisateur_id" bigint NOT NULL PRIMARY KEY REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "autres_specialites" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_enseignant_specialites" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "enseignant_id" bigint NOT NULL REFERENCES "Utilisateur_enseignant" ("utilisateur_id") DEFERRABLE INITIALLY DEFERRED, "specialite_id" bigint NOT NULL REFERENCES "Utilisateur_specialite" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_etudiant" ("utilisateur_id" bigint NOT NULL PRIMARY KEY REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_fonctionagent" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(50) NOT NULL UNIQUE, "nom" varchar(100) NOT NULL, "description" text NOT NULL, "responsabilites" text NOT NULL CHECK ((JSON_VALID("responsabilites") OR "responsabilites" IS NULL)), "controles" text NOT NULL CHECK ((JSON_VALID("controles") OR "controles" IS NULL)), "protocoles" text NOT NULL CHECK ((JSON_VALID("protocoles") OR "protocoles" IS NULL)), "role" varchar(20) NOT NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_fonctionagent_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "fonctionagent_id" bigint NOT NULL REFERENCES "Utilisateur_fonctionagent" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_genre" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(10) NOT NULL UNIQUE, "libelle" varchar(50) NOT NULL, "description" text NULL, "est_par_defaut" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_historicaladminsysteme" ("history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "utilisateur_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_historicalagentadministration" ("history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "utilisateur_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_historicalenseignant" ("autres_specialites" varchar(255) NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "utilisateur_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_historicaletudiant" ("history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "utilisateur_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_historicalparent" ("history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "utilisateur_id" bigint NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_historicalutilisateur" ("id" bigint NOT NULL, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "matricule" varchar(20) NOT NULL, "email" varchar(254) NULL, "telephone" varchar(20) NULL, "first_name" varchar(30) NOT NULL, "last_name" varchar(150) NOT NULL, "role" varchar(20) NOT NULL, "date_inscription" datetime NOT NULL, "date_nais" date NOT NULL, "doit_changer_mot_de_passe" bool NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "history_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "history_date" datetime NOT NULL, "history_change_reason" varchar(100) NULL, "history_type" varchar(1) NOT NULL, "genre_id" bigint NULL, "history_user_id" bigint NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_parent" ("utilisateur_id" bigint NOT NULL PRIMARY KEY REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_parent_enfants" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "parent_id" bigint NOT NULL REFERENCES "Utilisateur_parent" ("utilisateur_id") DEFERRABLE INITIALLY DEFERRED, "etudiant_id" bigint NOT NULL REFERENCES "Utilisateur_etudiant" ("utilisateur_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_rolepermission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "role" varchar(20) NOT NULL UNIQUE, "date_creation" datetime NOT NULL, "date_maj" datetime NOT NULL, "groupe_id" integer NULL UNIQUE REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_rolepermission_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "rolepermission_id" bigint NOT NULL REFERENCES "Utilisateur_rolepermission" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_specialite" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nom" varchar(100) NOT NULL UNIQUE, "description" text NOT NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_utilisateur" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "matricule" varchar(20) NOT NULL UNIQUE, "email" varchar(254) NULL, "telephone" varchar(20) NULL, "first_name" varchar(30) NOT NULL, "last_name" varchar(150) NOT NULL, "role" varchar(20) NOT NULL, "date_inscription" datetime NOT NULL, "date_nais" date NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "genre_id" bigint NULL REFERENCES "Utilisateur_genre" ("id") DEFERRABLE INITIALLY DEFERRED, "doit_changer_mot_de_passe" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "Utilisateur_utilisateur_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "utilisateur_id" bigint NOT NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "Utilisateur_utilisateur_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "utilisateur_id" bigint NOT NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "Utilisateur_utilisateur" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "Finance_document_auteur_id_78a519d4" ON "Finance_document" ("auteur_id");
CREATE INDEX "Finance_documentinscription_inscription_id_36afd89f" ON "Finance_documentinscription" ("inscription_id");
CREATE INDEX "Finance_frais_classe_id_ea4a0d79" ON "Finance_frais" ("classe_id");
CREATE INDEX "Finance_historicalfrais_classe_id_9b8f33b6" ON "Finance_historicalfrais" ("classe_id");
CREATE INDEX "Finance_historicalfrais_history_date_3f280802" ON "Finance_historicalfrais" ("history_date");
CREATE INDEX "Finance_historicalfrais_history_user_id_1e31a747" ON "Finance_historicalfrais" ("history_user_id");
CREATE INDEX "Finance_historicalfrais_id_078be976" ON "Finance_historicalfrais" ("id");
CREATE INDEX "Finance_historicalinscription_annee_academique_id_d4020c59" ON "Finance_historicalinscription" ("annee_academique_id");
CREATE INDEX "Finance_historicalinscription_classe_id_fd4bf306" ON "Finance_historicalinscription" ("classe_id");
CREATE INDEX "Finance_historicalinscription_etudiant_id_ee932f26" ON "Finance_historicalinscription" ("etudiant_id");
CREATE INDEX "Finance_historicalinscription_history_date_bf8d8c9b" ON "Finance_historicalinscription" ("history_date");
CREATE INDEX "Finance_historicalinscription_history_user_id_3cf809ac" ON "Finance_historicalinscription" ("history_user_id");
CREATE INDEX "Finance_historicalinscription_id_7877b3ca" ON "Finance_historicalinscription" ("id");
CREATE INDEX "Finance_historicalinscription_parcours_id_279aece3" ON "Finance_historicalinscription" ("parcours_id");
CREATE INDEX "Finance_historicalpaiement_etudiant_id_f3a2be2a" ON "Finance_historicalpaiement" ("etudiant_id");
CREATE INDEX "Finance_historicalpaiement_frais_id_8be72f66" ON "Finance_historicalpaiement" ("frais_id");
CREATE INDEX "Finance_historicalpaiement_history_date_16336fb1" ON "Finance_historicalpaiement" ("history_date");
CREATE INDEX "Finance_historicalpaiement_history_user_id_6e2a4e87" ON "Finance_historicalpaiement" ("history_user_id");
CREATE INDEX "Finance_historicalpaiement_id_0080a60c" ON "Finance_historicalpaiement" ("id");
CREATE INDEX "Finance_historicalpaiement_reference_85f22f5f" ON "Finance_historicalpaiement" ("reference");
CREATE INDEX "Finance_inscription_annee_academique_id_f5e9542f" ON "Finance_inscription" ("annee_academique_id");
CREATE INDEX "Finance_inscription_classe_id_249f99ba" ON "Finance_inscription" ("classe_id");
CREATE INDEX "Finance_inscription_etudiant_id_6daa2cc4" ON "Finance_inscription" ("etudiant_id");
CREATE INDEX "Finance_inscription_parcours_id_1b2ac4da" ON "Finance_inscription" ("parcours_id");
CREATE INDEX "Finance_notification_utilisateur_id_92bdf54b" ON "Finance_notification" ("utilisateur_id");
CREATE INDEX "Finance_paiement_etudiant_id_e5498b26" ON "Finance_paiement" ("etudiant_id");
CREATE INDEX "Finance_paiement_frais_id_4d62b048" ON "Finance_paiement" ("frais_id");
CREATE INDEX "Formation_classe_annee_academique_id_97581707" ON "Formation_classe" ("annee_academique_id");
CREATE INDEX "Formation_classe_formation_id_61c79929" ON "Formation_classe" ("formation_id");
CREATE INDEX "Formation_formation_parcours_id_d9da748a" ON "Formation_formation" ("parcours_id");
CREATE INDEX "Formation_historicalanneeacademique_history_date_f4d3987a" ON "Formation_historicalanneeacademique" ("history_date");
CREATE INDEX "Formation_historicalanneeacademique_history_user_id_c11775de" ON "Formation_historicalanneeacademique" ("history_user_id");
CREATE INDEX "Formation_historicalanneeacademique_id_fd9312db" ON "Formation_historicalanneeacademique" ("id");
CREATE INDEX "Formation_historicalanneeacademique_nom_0a6a6d3d" ON "Formation_historicalanneeacademique" ("nom");
CREATE INDEX "Formation_historicalclasse_annee_academique_id_93b8f3cc" ON "Formation_historicalclasse" ("annee_academique_id");
CREATE INDEX "Formation_historicalclasse_formation_id_0db3f168" ON "Formation_historicalclasse" ("formation_id");
CREATE INDEX "Formation_historicalclasse_history_date_9e30c015" ON "Formation_historicalclasse" ("history_date");
CREATE INDEX "Formation_historicalclasse_history_user_id_69efde8a" ON "Formation_historicalclasse" ("history_user_id");
CREATE INDEX "Formation_historicalclasse_id_50794392" ON "Formation_historicalclasse" ("id");
CREATE INDEX "Formation_historicalformation_history_date_b68c0f19" ON "Formation_historicalformation" ("history_date");
CREATE INDEX "Formation_historicalformation_history_user_id_ff115f1f" ON "Formation_historicalformation" ("history_user_id");
CREATE INDEX "Formation_historicalformation_id_360135d6" ON "Formation_historicalformation" ("id");
CREATE INDEX "Formation_historicalformation_parcours_id_dae370d6" ON "Formation_historicalformation" ("parcours_id");
CREATE INDEX "Formation_historicalparcours_history_date_c4cf6c88" ON "Formation_historicalparcours" ("history_date");
CREATE INDEX "Formation_historicalparcours_history_user_id_4d8afd18" ON "Formation_historicalparcours" ("history_user_id");
CREATE INDEX "Formation_historicalparcours_id_101296aa" ON "Formation_historicalparcours" ("id");
CREATE INDEX "Formation_historicalparcours_specification_id_eb8643f5" ON "Formation_historicalparcours" ("specification_id");
CREATE INDEX "Formation_historicalparcours_type_formation_id_d5913457" ON "Formation_historicalparcours" ("type_formation_id");
CREATE INDEX "Formation_parcours_specification_id_eaf1b15a" ON "Formation_parcours" ("specification_id");
CREATE INDEX "Formation_parcours_type_formation_id_73993bbd" ON "Formation_parcours" ("type_formation_id");
CREATE INDEX "Utilisateur_agentadministration_fonctions_agentadministration_id_ee7eaf3b" ON "Utilisateur_agentadministration_fonctions" ("agentadministration_id");
CREATE UNIQUE INDEX "Utilisateur_agentadministration_fonctions_agentadministration_id_fonctionagent_id_9cf335fa_uniq" ON "Utilisateur_agentadministration_fonctions" ("agentadministration_id", "fonctionagent_id");
CREATE INDEX "Utilisateur_agentadministration_fonctions_fonctionagent_id_fff45faf" ON "Utilisateur_agentadministration_fonctions" ("fonctionagent_id");
CREATE INDEX "Utilisateur_enseignant_specialites_enseignant_id_8beed188" ON "Utilisateur_enseignant_specialites" ("enseignant_id");
CREATE UNIQUE INDEX "Utilisateur_enseignant_specialites_enseignant_id_specialite_id_8001a09f_uniq" ON "Utilisateur_enseignant_specialites" ("enseignant_id", "specialite_id");
CREATE INDEX "Utilisateur_enseignant_specialites_specialite_id_b418ec25" ON "Utilisateur_enseignant_specialites" ("specialite_id");
CREATE INDEX "Utilisateur_fonctionagent_permissions_fonctionagent_id_27e34c91" ON "Utilisateur_fonctionagent_permissions" ("fonctionagent_id");
CREATE UNIQUE INDEX "Utilisateur_fonctionagent_permissions_fonctionagent_id_permission_id_24fc4ad9_uniq" ON "Utilisateur_fonctionagent_permissions" ("fonctionagent_id", "permission_id");
CREATE INDEX "Utilisateur_fonctionagent_permissions_permission_id_e3ef9117" ON "Utilisateur_fonctionagent_permissions" ("permission_id");
CREATE INDEX "Utilisateur_historicaladminsysteme_history_date_dffba0ef" ON "Utilisateur_historicaladminsysteme" ("history_date");
CREATE INDEX "Utilisateur_historicaladminsysteme_history_user_id_371dc615" ON "Utilisateur_historicaladminsysteme" ("history_user_id");
CREATE INDEX "Utilisateur_historicaladminsysteme_utilisateur_id_4a3fd278" ON "Utilisateur_historicaladminsysteme" ("utilisateur_id");
CREATE INDEX "Utilisateur_historicalagentadministration_history_date_62c92646" ON "Utilisateur_historicalagentadministration" ("history_date");
CREATE INDEX "Utilisateur_historicalagentadministration_history_user_id_18644699" ON "Utilisateur_historicalagentadministration" ("history_user_id");
CREATE INDEX "Utilisateur_historicalagentadministration_utilisateur_id_5ce51c34" ON "Utilisateur_historicalagentadministration" ("utilisateur_id");
CREATE INDEX "Utilisateur_historicalenseignant_history_date_93f8e923" ON "Utilisateur_historicalenseignant" ("history_date");
CREATE INDEX "Utilisateur_historicalenseignant_history_user_id_bcf7421b" ON "Utilisateur_historicalenseignant" ("history_user_id");
CREATE INDEX "Utilisateur_historicalenseignant_utilisateur_id_e5e7b937" ON "Utilisateur_historicalenseignant" ("utilisateur_id");
CREATE INDEX "Utilisateur_historicaletudiant_history_date_974bf1f3" ON "Utilisateur_historicaletudiant" ("history_date");
CREATE INDEX "Utilisateur_historicaletudiant_history_user_id_ae37b8b8" ON "Utilisateur_historicaletudiant" ("history_user_id");
CREATE INDEX "Utilisateur_historicaletudiant_utilisateur_id_2a0e94b6" ON "Utilisateur_historicaletudiant" ("utilisateur_id");
CREATE INDEX "Utilisateur_historicalparent_history_date_aa28f432" ON "Utilisateur_historicalparent" ("history_date");
CREATE INDEX "Utilisateur_historicalparent_history_user_id_4b644a0d" ON "Utilisateur_historicalparent" ("history_user_id");
CREATE INDEX "Utilisateur_historicalparent_utilisateur_id_707ed492" ON "Utilisateur_historicalparent" ("utilisateur_id");
CREATE INDEX "Utilisateur_historicalutilisateur_genre_id_0114515b" ON "Utilisateur_historicalutilisateur" ("genre_id");
CREATE INDEX "Utilisateur_historicalutilisateur_history_date_8bc29a96" ON "Utilisateur_historicalutilisateur" ("history_date");
CREATE INDEX "Utilisateur_historicalutilisateur_history_user_id_ded493c6" ON "Utilisateur_historicalutilisateur" ("history_user_id");
CREATE INDEX "Utilisateur_historicalutilisateur_id_6ca6d67b" ON "Utilisateur_historicalutilisateur" ("id");
CREATE INDEX "Utilisateur_historicalutilisateur_matricule_978938b1" ON "Utilisateur_historicalutilisateur" ("matricule");
CREATE INDEX "Utilisateur_parent_enfants_etudiant_id_3c764d44" ON "Utilisateur_parent_enfants" ("etudiant_id");
CREATE INDEX "Utilisateur_parent_enfants_parent_id_09cae3aa" ON "Utilisateur_parent_enfants" ("parent_id");
CREATE UNIQUE INDEX "Utilisateur_parent_enfants_parent_id_etudiant_id_a3f00d72_uniq" ON "Utilisateur_parent_enfants" ("parent_id", "etudiant_id");
CREATE INDEX "Utilisateur_rolepermission_permissions_permission_id_fc590b15" ON "Utilisateur_rolepermission_permissions" ("permission_id");
CREATE INDEX "Utilisateur_rolepermission_permissions_rolepermission_id_a3092979" ON "Utilisateur_rolepermission_permissions" ("rolepermission_id");
CREATE UNIQUE INDEX "Utilisateur_rolepermission_permissions_rolepermission_id_permission_id_0025996f_uniq" ON "Utilisateur_rolepermission_permissions" ("rolepermission_id", "permission_id");
CREATE INDEX "Utilisateur_utilisateur_genre_id_f5a957da" ON "Utilisateur_utilisateur" ("genre_id");
CREATE INDEX "Utilisateur_utilisateur_groups_group_id_47f1d85a" ON "Utilisateur_utilisateur_groups" ("group_id");
CREATE INDEX "Utilisateur_utilisateur_groups_utilisateur_id_a4666844" ON "Utilisateur_utilisateur_groups" ("utilisateur_id");
CREATE UNIQUE INDEX "Utilisateur_utilisateur_groups_utilisateur_id_group_id_cff792c6_uniq" ON "Utilisateur_utilisateur_groups" ("utilisateur_id", "group_id");
CREATE INDEX "Utilisateur_utilisateur_user_permissions_permission_id_e9f382e5" ON "Utilisateur_utilisateur_user_permissions" ("permission_id");
CREATE INDEX "Utilisateur_utilisateur_user_permissions_utilisateur_id_de39a63d" ON "Utilisateur_utilisateur_user_permissions" ("utilisateur_id");
CREATE UNIQUE INDEX "Utilisateur_utilisateur_user_permissions_utilisateur_id_permission_id_ff925b9e_uniq" ON "Utilisateur_utilisateur_user_permissions" ("utilisateur_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;
