# Generated by Django 5.2.1 on 2025-06-19 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='2023-2024', max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('classes_standards_creees', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('duree', models.IntegerField(help_text='Durée en mois/années selon le type')),
                ('est_professionnelle', models.BooleanField(default=False)),
                ('avec_classes', models.BooleanField(default=True, help_text='Cocher pour créer automatiquement les classes')),
            ],
            options={
                'ordering': ['parcours__type_formation__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_serie', models.CharField(blank=True, max_length=3, null=True)),
                ('structure_classes', models.JSONField(blank=True, default=list, help_text='Liste JSON des classes — automatiquement héritée du type de formation')),
                ('diplome_final', models.CharField(blank=True, help_text='Ex: BAC A, BEPC, CAP', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Parcours',
                'ordering': ['type_formation', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Spécification',
                'verbose_name_plural': 'Spécifications',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('liste_classe', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Type de formation',
                'verbose_name_plural': 'Types de formation',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.anneeacademique')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Formation.formation')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='Formation.parcours'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Formation.specification'),
        ),
        migrations.AddField(
            model_name='parcours',
            name='type_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.typeformation'),
        ),
    ]
