# Generated by Django 5.2.1 on 2025-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.IntegerField(blank=True, help_text='Durée en mois/années selon le type', null=True),
        ),
    ]
