# Generated by Django 4.2.12 on 2025-11-12 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparcours',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalparcours',
            name='specification',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.specification'),
        ),
        migrations.AddField(
            model_name='historicalparcours',
            name='type_formation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.typeformation'),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalformation',
            name='parcours',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.parcours'),
        ),
        migrations.AddField(
            model_name='historicalclasse',
            name='annee_academique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.anneeacademique'),
        ),
        migrations.AddField(
            model_name='historicalclasse',
            name='formation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Formation.formation'),
        ),
        migrations.AddField(
            model_name='historicalclasse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanneeacademique',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formation',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='Formation.parcours'),
        ),
        migrations.AddField(
            model_name='classe',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.anneeacademique'),
        ),
        migrations.AddField(
            model_name='classe',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Formation.formation'),
        ),
    ]
