# Generated by Django 4.2.12 on 2025-11-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('roles_autorises', models.CharField(max_length=200)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Métadonnée de permission',
                'verbose_name_plural': 'Métadonnées de permissions',
            },
        ),
    ]
